import type { CallItem, ChatPreview, StatusItem } from "./types";

export const chats: ChatPreview[] = [
  {
    id: "unknown-1",
    friendName: "+234 321 765 4321",
    friendStatus: "Online",
    imgName: "unknown-contact",
    imgFormat: "png",
    lastMessage: "typing...",
    time: "08:23 PM",
    unreadCount: 7,
    isTyping: true,
  },
  {
    id: "barakat",
    friendName: "Barakat Tech Sis",
    friendStatus: "last seen 8:05 PM",
    imgName: "barakat",
    imgFormat: "jpg",
    lastMessage:
      "I have merged your pull request, you can continue on the config.test.js file",
    time: "08:09 PM",
    unreadCount: 0,
    hasCheckmark: true,
    checkmarkColor: "#8696A0",
    messageClassName: "long-text-with-marks",
  },
  {
    id: "ife",
    friendName: "Ife",
    friendStatus: "last seen 06:43 PM",
    imgName: "ife",
    imgFormat: "jpg",
    lastMessage: "meet me at law",
    time: "07:12 PM",
    unreadCount: 1,
  },
  {
    id: "pharaohs",
    friendName: "💻 Programming Pharaohs 👑🏹",
    friendStatus: "tap here for group info",
    imgName: "pharaohs",
    imgFormat: "jpg",
    lastMessage:
      "Async-Abeeb ⚛: A web developer(HTML, CSS, Bootstrap and basic Javascript) is needed at Ajah and Lekki Lagos.",
    time: "06:11 PM",
    unreadCount: 243,
    messageClassName: "long-text",
  },
  {
    id: "barber",
    friendName: "My Barber",
    friendStatus: "Online",
    imgName: "barber",
    imgFormat: "jpeg",
    lastMessage: "When you dey come?",
    time: "04:23 PM",
    unreadCount: 4,
  },
  {
    id: "ibrahim",
    friendName: "Ibro 007",
    friendStatus: "01:58 PM",
    imgName: "ibrahim",
    imgFormat: "jpg",
    lastMessage: "🙃",
    time: "02:13 PM",
    unreadCount: 0,
    hasCheckmark: true,
    checkmarkColor: "#3281e7",
  },
  {
    id: "dynamo",
    friendName: "Dynamo Devs 💣💻🔥",
    friendStatus: "tap here for group info",
    imgName: "dynamo-devs",
    imgFormat: "jpg",
    lastMessage:
      "Bomb-Codes👨🏾‍💻: Flutter Dev needed, Onsite and full-time(Ikeja GRA, Lagos) 2-3yrs. experience",
    time: "02:05 PM",
    unreadCount: 74,
    messageClassName: "long-text",
  },
  {
    id: "larry",
    friendName: "Designer Larry",
    friendStatus: "last seen 12:15 PM",
    imgName: "designer-larry",
    imgFormat: "jpg",
    lastMessage:
      "kindly check that figma file. I have made some changes to the colour of the buttons in the about-us section.",
    time: "12:12 PM",
    unreadCount: 2,
    messageClassName: "long-text",
  },
  {
    id: "muiz",
    friendName: "Muiz",
    friendStatus: "11:06 AM",
    imgName: "muiz",
    imgFormat: "jpg",
    lastMessage: "0:56",
    time: "11:17 AM",
    unreadCount: 3,
    hasMic: true,
  },
  {
    id: "teslim",
    friendName: "Teslim",
    friendStatus: "last seen 05:38 PM",
    imgName: "teslim",
    imgFormat: "jpg",
    lastMessage: 'you reacted 👍🏾 to "will message you on that project soon"',
    time: "10:13 AM",
    unreadCount: 0,
    hasCheckmark: true,
    checkmarkColor: "#3281e7",
    messageClassName: "long-text-with-marks",
  },
  {
    id: "seun",
    friendName: "Seun",
    friendStatus: "last seen Yesterday",
    imgName: "unknown-contact",
    imgFormat: "png",
    lastMessage: "recording audio...",
    time: "12:12 PM",
    unreadCount: 0,
    isRecording: true,
    messageClassName: "long-text",
  },
  {
    id: "agric",
    friendName: "Agricultural Research Group",
    friendStatus: "tap here for group info",
    imgName: "agric-group",
    imgFormat: "jpg",
    lastMessage: "Agbe-ni-Gold is typing...",
    time: "Yesterday",
    unreadCount: 102,
    isTyping: true,
    messageClassName: "long-text",
  },
  {
    id: "flier",
    friendName: "Flier Client (GDSC Ilorin)",
    friendStatus: "last seen now",
    imgName: "flier-client",
    imgFormat: "jpg",
    lastMessage:
      "Photos. These are the images you asked for. I would like that no. 1 to be in the flier.",
    time: "Yesterday",
    unreadCount: 15,
    hasPhoto: true,
    messageClassName: "long-text-with-marks",
  },
];

export const statusItems: StatusItem[] = [
  {
    id: "my-status",
    name: "My Status",
    time: "Today, 3:08 PM",
    img: "/imgs/status/my-status.jpg",
    ringClass: "status-9",
    showMenu: true,
  },
  {
    id: "amazin-tv",
    name: "Amazin' TV",
    time: "1 minute ago",
    img: "/imgs/status/amazin-tv.jpg",
    ringClass: "status-21",
  },
  {
    id: "naija",
    name: "Naija Unveiled",
    time: "12 minutes ago",
    img: "/imgs/status/naija-unveiled.jpg",
    ringClass: "status-9",
  },
  {
    id: "micheal",
    name: "Bro. Micheal",
    time: "37 minutes ago",
    img: "/imgs/status/bro-micheal.jpg",
    ringClass: "status-4",
  },
  {
    id: "science",
    name: "Science Archives",
    time: "52 minutes ago",
    img: "/imgs/status/science-archives.jpg",
    ringClass: "status-12",
  },
  {
    id: "aderinsola",
    name: "Aderinsola",
    time: "8:04 PM",
    timeDesktop: "Today, 8:04 PM",
    img: "/imgs/status/aderinsola.jpg",
    ringClass: "status-1",
  },
  {
    id: "army",
    name: "Army Analytics",
    time: "6:49 PM",
    timeDesktop: "Today, 6:49 PM",
    img: "/imgs/status/army-analytics.jpg",
    ringClass: "status-9",
  },
  {
    id: "ai-pulse",
    name: "AI Pulse",
    time: "5:17 PM",
    timeDesktop: "Today, 5:17 PM",
    img: "/imgs/status/ai-pulse.jpg",
    ringClass: "status-12",
  },
  {
    id: "barakat-status",
    name: "Barakat Tech Sis",
    time: "2:40 PM",
    timeDesktop: "Today, 2:40 PM",
    img: "/imgs/status/barakat-tech-sis.jpg",
    ringClass: "status-4",
  },
  {
    id: "james",
    name: "James",
    time: "2:37 PM",
    timeDesktop: "Today, 2:37 PM",
    img: "/imgs/status/james.jpg",
    ringClass: "status-1",
  },
  {
    id: "larry-status",
    name: "Designer Larry",
    time: "11:05 AM",
    timeDesktop: "Today, 11:05 AM",
    img: "/imgs/status/designer-larry.jpg",
    ringClass: "status-12",
  },
  {
    id: "abdullahi",
    name: "Abdullahi",
    time: "9:29 AM",
    timeDesktop: "Today, 9:29 AM",
    img: "/imgs/status/abdullahi.jpg",
    ringClass: "status-1",
  },
  {
    id: "musa",
    name: "Musa",
    time: "Yesterday",
    timeDesktop: "Yesterday, 8:02 PM",
    img: "/imgs/status/musa.jpg",
    ringClass: "status-1",
  },
  {
    id: "abdul-kareem",
    name: "Abdul-Kareem",
    time: "Yesterday",
    timeDesktop: "Yesterday, 7:33 PM",
    img: "/imgs/status/abdul-kareem.jpg",
    ringClass: "status-1",
  },
];

export const callItems: CallItem[] = [
  {
    id: "ife-1",
    name: "Ife",
    img: "/imgs/friends/ife.jpg",
    direction: "outgoing",
    time: "(2) Today, 12:06 PM",
  },
  {
    id: "ife-2",
    name: "Ife",
    img: "/imgs/friends/ife.jpg",
    direction: "incoming",
    time: "(2) Yesterday 10:42 PM",
    missed: true,
  },
  {
    id: "agric-1",
    name: "Agricultural Research group",
    img: "/imgs/friends/agric-group.jpg",
    direction: "incoming",
    time: "Yesterday 9:25 PM",
    missed: true,
  },
  {
    id: "seun-1",
    name: "Seun",
    img: "/imgs/friends/unknown-contact.png",
    direction: "incoming",
    time: "June 9, 9:53 PM",
  },
  {
    id: "seun-2",
    name: "Seun",
    img: "/imgs/friends/unknown-contact.png",
    direction: "incoming",
    time: "June 9, 9:55 AM",
    missed: true,
  },
  {
    id: "agric-2",
    name: "Agricultural Research group",
    img: "/imgs/friends/agric-group.jpg",
    direction: "incoming",
    time: "June 8, 9:45 PM",
  },
  {
    id: "aishat",
    name: "Aishat",
    img: "/imgs/friends/unknown-contact.png",
    direction: "incoming",
    time: "(3) June 7, 8:51 PM",
    missed: true,
  },
];

export function friendImagePath(imgName: string, imgFormat: string) {
  return `/imgs/friends/${imgName}.${imgFormat}`;
}
