import type { CallItem, ChatPreview, StatusItem } from "./types";

export const chats: ChatPreview[] = [
  {
    id: "gong-bot",
    friendName: "gong gang",
    friendStatus: "Online",
    imgName: "gong_icon",
    imgFormat: "png",
    imgSrc: "/imgs/gong_icon.png",
    lastMessage: "test one",
    time: "12:45 PM",
    unreadCount: 0,
  },
];

export const statusItems: StatusItem[] = [
  {
    id: "my-status",
    name: "My Status",
    time: "Today, 3:08 PM",
    img: "/imgs/status/my-status.jpg",
    ringClass: "status-9",
    showMenu: true,
  },
  {
    id: "amazin-tv",
    name: "Amazin' TV",
    time: "1 minute ago",
    img: "/imgs/status/amazin-tv.jpg",
    ringClass: "status-21",
  },
  {
    id: "naija",
    name: "Naija Unveiled",
    time: "12 minutes ago",
    img: "/imgs/status/naija-unveiled.jpg",
    ringClass: "status-9",
  },
  {
    id: "micheal",
    name: "Bro. Micheal",
    time: "37 minutes ago",
    img: "/imgs/status/bro-micheal.jpg",
    ringClass: "status-4",
  },
  {
    id: "science",
    name: "Science Archives",
    time: "52 minutes ago",
    img: "/imgs/status/science-archives.jpg",
    ringClass: "status-12",
  },
  {
    id: "aderinsola",
    name: "Aderinsola",
    time: "8:04 PM",
    timeDesktop: "Today, 8:04 PM",
    img: "/imgs/status/aderinsola.jpg",
    ringClass: "status-1",
  },
  {
    id: "army",
    name: "Army Analytics",
    time: "6:49 PM",
    timeDesktop: "Today, 6:49 PM",
    img: "/imgs/status/army-analytics.jpg",
    ringClass: "status-9",
  },
  {
    id: "ai-pulse",
    name: "AI Pulse",
    time: "5:17 PM",
    timeDesktop: "Today, 5:17 PM",
    img: "/imgs/status/ai-pulse.jpg",
    ringClass: "status-12",
  },
  {
    id: "barakat-status",
    name: "Barakat Tech Sis",
    time: "2:40 PM",
    timeDesktop: "Today, 2:40 PM",
    img: "/imgs/status/barakat-tech-sis.jpg",
    ringClass: "status-4",
  },
  {
    id: "james",
    name: "James",
    time: "2:37 PM",
    timeDesktop: "Today, 2:37 PM",
    img: "/imgs/status/james.jpg",
    ringClass: "status-1",
  },
  {
    id: "larry-status",
    name: "Designer Larry",
    time: "11:05 AM",
    timeDesktop: "Today, 11:05 AM",
    img: "/imgs/status/designer-larry.jpg",
    ringClass: "status-12",
  },
  {
    id: "abdullahi",
    name: "Abdullahi",
    time: "9:29 AM",
    timeDesktop: "Today, 9:29 AM",
    img: "/imgs/status/abdullahi.jpg",
    ringClass: "status-1",
  },
  {
    id: "musa",
    name: "Musa",
    time: "Yesterday",
    timeDesktop: "Yesterday, 8:02 PM",
    img: "/imgs/status/musa.jpg",
    ringClass: "status-1",
  },
  {
    id: "abdul-kareem",
    name: "Abdul-Kareem",
    time: "Yesterday",
    timeDesktop: "Yesterday, 7:33 PM",
    img: "/imgs/status/abdul-kareem.jpg",
    ringClass: "status-1",
  },
];

export const callItems: CallItem[] = [
  {
    id: "ife-1",
    name: "Ife",
    img: "/imgs/friends/ife.jpg",
    direction: "outgoing",
    time: "(2) Today, 12:06 PM",
  },
  {
    id: "ife-2",
    name: "Ife",
    img: "/imgs/friends/ife.jpg",
    direction: "incoming",
    time: "(2) Yesterday 10:42 PM",
    missed: true,
  },
  {
    id: "agric-1",
    name: "Agricultural Research group",
    img: "/imgs/friends/agric-group.jpg",
    direction: "incoming",
    time: "Yesterday 9:25 PM",
    missed: true,
  },
  {
    id: "seun-1",
    name: "Seun",
    img: "/imgs/friends/unknown-contact.png",
    direction: "incoming",
    time: "June 9, 9:53 PM",
  },
  {
    id: "seun-2",
    name: "Seun",
    img: "/imgs/friends/unknown-contact.png",
    direction: "incoming",
    time: "June 9, 9:55 AM",
    missed: true,
  },
  {
    id: "agric-2",
    name: "Agricultural Research group",
    img: "/imgs/friends/agric-group.jpg",
    direction: "incoming",
    time: "June 8, 9:45 PM",
  },
  {
    id: "aishat",
    name: "Aishat",
    img: "/imgs/friends/unknown-contact.png",
    direction: "incoming",
    time: "(3) June 7, 8:51 PM",
    missed: true,
  },
];

export function friendImagePath(imgName: string, imgFormat: string, imgSrc?: string) {
  return imgSrc ?? `/imgs/friends/${imgName}.${imgFormat}`;
}
